services:
  - type: web
    name: image-restoration-backend
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT